//
//  BanditModels.swift
//  AC
//

import Foundation

// MARK: - BanditScreenState

/// Structured output from Brain 1 (VLM extraction call).
///
/// The VLM looks at the screenshot and returns a compact JSON assessment. The bandit
/// algorithm uses this to build a feature vector and decide whether to show the
/// `candidateNudge`.  BrainService never needs to know what's on screen — it only
/// sees this struct.
struct BanditScreenState: Codable, Sendable {
    var appCategory: AppCategory
    /// Productivity alignment with the user's stated goals. 0.0 = pure distraction, 1.0 = fully on-task.
    var productivityScore: Double
    var onTask: Bool
    /// What's on screen in ≤12 words, no PII, no URLs.
    var contentSummary: String
    /// VLM's confidence in this classification (0.0–1.0).
    var confidence: Double
    /// Optional nudge pre-generated by the VLM. The bandit decides whether to show it.
    var candidateNudge: String?

    enum AppCategory: String, Codable, Sendable, CaseIterable {
        case productivity
        case communication
        case browser
        case entertainment
        case social
        case development
        case reference
        case other
    }
}

// MARK: - BanditFeatureVector

/// 16-dimensional feature vector used as LinUCB context.
///
/// Dimension layout (kept stable — never reorder without resetting engine weights):
/// ```
/// [0]     bias = 1.0
/// [1]     sin(2π × hour/24)          — cyclical time encoding
/// [2]     cos(2π × hour/24)
/// [3]     is_weekend (1.0 / 0.0)
/// [4..11] app_category one-hot over AppCategory.allCases (8 values)
/// [12]    productivityScore (0.0–1.0)
/// [13]    log1p(timeInAppMinutes)     — log-normalised, ≥0
/// [14]    log1p(minutesSinceLastNudge capped at 120)
/// [15]    lastNudgeReaction (+1 positive / -1 negative / 0 unknown)
/// ```
struct BanditFeatureVector: Codable, Sendable, Equatable {
    var values: [Double]

    static let dimension = 16

    static func build(
        screenState: BanditScreenState,
        now: Date,
        timeInAppSeconds: TimeInterval,
        timeSinceLastNudgeSeconds: TimeInterval?,
        lastNudgeWasPositive: Bool?
    ) -> BanditFeatureVector {
        let calendar = Calendar.current
        let hour = Double(calendar.component(.hour, from: now))
            + Double(calendar.component(.minute, from: now)) / 60.0
        let weekday = calendar.component(.weekday, from: now)  // 1=Sun, 7=Sat

        var v = [Double](repeating: 0, count: dimension)

        v[0] = 1.0  // bias
        v[1] = sin(2 * .pi * hour / 24)
        v[2] = cos(2 * .pi * hour / 24)
        v[3] = (weekday == 1 || weekday == 7) ? 1.0 : 0.0

        // One-hot over AppCategory.allCases (indices 4..11)
        if let idx = BanditScreenState.AppCategory.allCases.firstIndex(of: screenState.appCategory) {
            v[4 + idx] = 1.0
        }

        v[12] = max(0, min(1, screenState.productivityScore))
        v[13] = log1p(max(0, timeInAppSeconds / 60))
        v[14] = log1p(min(120, (timeSinceLastNudgeSeconds ?? 120) / 60))
        v[15] = lastNudgeWasPositive.map { $0 ? 1.0 : -1.0 } ?? 0.0

        return BanditFeatureVector(values: v)
    }
}

// MARK: - BanditFocusAlgorithmState

/// Persistent state slice for `BanditMonitoringAlgorithm`.
///
/// Stored in `AlgorithmStateEnvelope.banditFocus` and persisted to `state.json`.
struct BanditFocusAlgorithmState: Codable, Sendable, Equatable {
    /// The LinUCB bandit engine — accumulates weights over time.
    var engine = ContextualBanditEngine()

    // Pending nudge — saved at nudge time, consumed when reward arrives.
    var pendingNudgeContext: BanditFeatureVector?
    var pendingNudgeEvaluationID: String?
    var pendingNudgeIssuedAt: Date?

    // Spam-prevention state (same role as LLMFocusAlgorithmState.distraction).
    var distraction = DistractionMetadata()
    var lastVisualCheckByContext: [String: Date] = [:]

    // Used to build the next feature vector.
    var lastNudgeWasPositive: Bool?
    var lastNudgeAt: Date?
}
