//
//  BanditModels.swift
//  AC
//

import Foundation

// MARK: - BanditScreenState

/// Structured output from Brain 1 (VLM extraction call).
///
/// The VLM looks at the screenshot and returns a compact JSON assessment. The bandit
/// algorithm uses this to build a feature vector and pick an action. BrainService never
/// needs to know what's on screen — it only sees this struct.
struct BanditScreenState: Codable, Sendable {
    var appCategory: AppCategory
    /// Productivity alignment with the user's stated goals. 0.0 = pure distraction, 1.0 = fully on-task.
    var productivityScore: Double
    var onTask: Bool
    /// What's on screen in ≤12 words, no PII, no URLs.
    var contentSummary: String
    /// VLM's confidence in this classification (0.0–1.0).
    var confidence: Double
    /// Optional fallback nudge pre-generated by the VLM. The bandit prefers a copywriter-authored
    /// nudge that matches the chosen arm's tone; this is the safety net.
    var candidateNudge: String?

    enum AppCategory: String, Codable, Sendable, CaseIterable {
        case productivity
        case communication
        case browser
        case entertainment
        case social
        case development
        case reference
        case other
    }
}

// MARK: - BanditFeatureVector

/// 16-dimensional feature vector used as LinUCB context.
///
/// Dimension layout (kept stable — never reorder without resetting engine weights):
/// ```
/// [0]     bias = 1.0
/// [1]     sin(2π × hour/24)          — cyclical time encoding
/// [2]     cos(2π × hour/24)
/// [3]     is_weekend (1.0 / 0.0)
/// [4..11] app_category one-hot over AppCategory.allCases (8 values)
/// [12]    productivityScore (0.0–1.0)
/// [13]    log1p(timeInAppMinutes)     — log-normalised, ≥0
/// [14]    log1p(minutesSinceLastNudge capped at 120)
/// [15]    lastNudgeReaction (+1 positive / -1 negative / 0 unknown)
/// ```
struct BanditFeatureVector: Codable, Sendable, Equatable {
    var values: [Double]

    static let dimension = 16

    static func build(
        screenState: BanditScreenState,
        now: Date,
        timeInAppSeconds: TimeInterval,
        timeSinceLastNudgeSeconds: TimeInterval?,
        lastNudgeWasPositive: Bool?
    ) -> BanditFeatureVector {
        let calendar = Calendar.current
        let hour = Double(calendar.component(.hour, from: now))
            + Double(calendar.component(.minute, from: now)) / 60.0
        let weekday = calendar.component(.weekday, from: now)  // 1=Sun, 7=Sat

        var v = [Double](repeating: 0, count: dimension)

        v[0] = 1.0  // bias
        v[1] = sin(2 * .pi * hour / 24)
        v[2] = cos(2 * .pi * hour / 24)
        v[3] = (weekday == 1 || weekday == 7) ? 1.0 : 0.0

        if let idx = BanditScreenState.AppCategory.allCases.firstIndex(of: screenState.appCategory) {
            v[4 + idx] = 1.0
        }

        v[12] = max(0, min(1, screenState.productivityScore))
        v[13] = log1p(max(0, timeInAppSeconds / 60))
        v[14] = log1p(min(120, (timeSinceLastNudgeSeconds ?? 120) / 60))
        v[15] = lastNudgeWasPositive.map { $0 ? 1.0 : -1.0 } ?? 0.0

        return BanditFeatureVector(values: v)
    }
}

// MARK: - BanditFocusAlgorithmState

/// Persistent state slice for `BanditMonitoringAlgorithm`.
///
/// Stored in `AlgorithmStateEnvelope.banditFocus` and persisted to `state.json`.
struct BanditFocusAlgorithmState: Codable, Sendable, Equatable {
    /// The multi-arm LinUCB bandit engine — accumulates weights over time.
    var engine = ContextualBanditEngine()

    // Pending nudge — saved at action time, consumed when reward arrives.
    var pendingNudgeContext: BanditFeatureVector?
    var pendingNudgeEvaluationID: String?
    var pendingNudgeIssuedAt: Date?
    /// Arm that fired the pending intervention — learning target when the reward lands.
    var pendingArm: BanditArm?

    /// Per-context timestamp of the last intervention. Drives the bandit's minimal
    /// anti-spam cooldown (see `BanditCooldown`).
    var lastInterventionByContext: [String: Date] = [:]

    /// Current context key — used by `BanditCooldown` to gate the stability window.
    /// Transient: if a persisted state restores without this, the first tick after
    /// start-up will repopulate via `noteContext`.
    var currentContextKey: String?
    var currentContextEnteredAt: Date?

    // Used to build the next feature vector.
    var lastNudgeWasPositive: Bool?
    var lastNudgeAt: Date?

    // MARK: - Codable (with migration from DistractionLadder-era fields)

    enum CodingKeys: String, CodingKey {
        case engine
        case pendingNudgeContext
        case pendingNudgeEvaluationID
        case pendingNudgeIssuedAt
        case pendingArm
        case lastInterventionByContext
        case currentContextKey
        case currentContextEnteredAt
        case lastNudgeWasPositive
        case lastNudgeAt
        // Legacy keys — read-only for migration from state.json written before the bandit
        // stopped sharing the DistractionLadder.
        case distraction
        case lastVisualCheckByContext
    }

    init() {}

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        engine = try c.decodeIfPresent(ContextualBanditEngine.self, forKey: .engine) ?? ContextualBanditEngine()
        pendingNudgeContext = try c.decodeIfPresent(BanditFeatureVector.self, forKey: .pendingNudgeContext)
        pendingNudgeEvaluationID = try c.decodeIfPresent(String.self, forKey: .pendingNudgeEvaluationID)
        pendingNudgeIssuedAt = try c.decodeIfPresent(Date.self, forKey: .pendingNudgeIssuedAt)
        pendingArm = try c.decodeIfPresent(BanditArm.self, forKey: .pendingArm)
        lastInterventionByContext =
            try c.decodeIfPresent([String: Date].self, forKey: .lastInterventionByContext)
            ?? c.decodeIfPresent([String: Date].self, forKey: .lastVisualCheckByContext)
            ?? [:]
        currentContextKey = try c.decodeIfPresent(String.self, forKey: .currentContextKey)
        currentContextEnteredAt = try c.decodeIfPresent(Date.self, forKey: .currentContextEnteredAt)
        lastNudgeWasPositive = try c.decodeIfPresent(Bool.self, forKey: .lastNudgeWasPositive)
        lastNudgeAt = try c.decodeIfPresent(Date.self, forKey: .lastNudgeAt)
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(engine, forKey: .engine)
        try c.encodeIfPresent(pendingNudgeContext, forKey: .pendingNudgeContext)
        try c.encodeIfPresent(pendingNudgeEvaluationID, forKey: .pendingNudgeEvaluationID)
        try c.encodeIfPresent(pendingNudgeIssuedAt, forKey: .pendingNudgeIssuedAt)
        try c.encodeIfPresent(pendingArm, forKey: .pendingArm)
        try c.encode(lastInterventionByContext, forKey: .lastInterventionByContext)
        try c.encodeIfPresent(currentContextKey, forKey: .currentContextKey)
        try c.encodeIfPresent(currentContextEnteredAt, forKey: .currentContextEnteredAt)
        try c.encodeIfPresent(lastNudgeWasPositive, forKey: .lastNudgeWasPositive)
        try c.encodeIfPresent(lastNudgeAt, forKey: .lastNudgeAt)
    }
}
